# Generated by Django 5.1.6 on 2025-02-07 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('userName', models.CharField(default='', max_length=150)),
                ('userEmail', models.EmailField(default='', max_length=254)),
                ('userAge', models.IntegerField(default=0)),
            ],
        ),
    ]
