# Generated by Django 5.1.6 on 2025-02-07 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(default='', max_length=100)),
                ('userTask', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
